---
- hosts: "{{ target }}"
  gather_facts: no
  tasks:
    - name: stop node - stop avalanchego
      shell: sudo systemctl stop avalanchego
    - name: replace subnet EVM binary
      shell: cp subnet-evm "{{ subnetEVMBinaryPath }}"
    - name: stop start - start avalanchego
      shell: sudo systemctl start avalanchego
