{
 "title": "Database",
 "tags": [ "Odyssey" ],
 "time": { "from": "now-1h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Database Read Rate",
   "type": "timeseries",
   "description": "Database read rate. Note that these reads may be from caches and not from disk.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(odyssey_db_read_size_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "Bytes Read"
    }
   ]
  },
  {
   "title": "Database Write Rate",
   "type": "timeseries",
   "description": "Database write rate.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "expr": "rate(odyssey_db_write_size_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "Write Rate"
    }
   ]
  },
  {
   "title": "Total Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second across all chains",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(odyssey_db_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(odyssey_db_get_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(odyssey_db_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(odyssey_db_has_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(odyssey_db_compact_size_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(odyssey_db_batch_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(odyssey_db_batch_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(odyssey_db_batch_reset_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(odyssey_db_batch_replay_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "Total Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(odyssey_db_put_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(odyssey_db_get_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_get_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(odyssey_db_delete_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(odyssey_db_has_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_has_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(odyssey_db_compact_size_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_compact_size_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(odyssey_db_batch_put_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_batch_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(odyssey_db_batch_delete_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_batch_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(odyssey_db_batch_reset_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_batch_reset_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(odyssey_db_batch_replay_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_batch_replay_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "A-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second on A-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(odyssey_X_db_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(odyssey_X_db_get_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(odyssey_X_db_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(odyssey_X_db_has_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(odyssey_X_db_compact_size_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(odyssey_X_db_batch_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(odyssey_X_db_batch_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(odyssey_X_db_batch_reset_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(odyssey_X_db_batch_replay_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "A-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on A-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(odyssey_X_db_put_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_X_db_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(odyssey_X_db_get_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_X_db_get_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(odyssey_X_db_delete_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_X_db_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(odyssey_X_db_has_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_X_db_has_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(odyssey_X_db_compact_size_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_X_db_compact_size_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(odyssey_X_db_batch_put_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_X_db_batch_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(odyssey_X_db_batch_delete_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_X_db_batch_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(odyssey_X_db_batch_reset_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_X_db_batch_reset_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(odyssey_X_db_batch_replay_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_X_db_batch_replay_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "O-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second on O-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(odyssey_P_db_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(odyssey_P_db_get_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(odyssey_P_db_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(odyssey_P_db_has_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(odyssey_P_db_compact_size_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(odyssey_P_db_batch_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(odyssey_P_db_batch_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(odyssey_P_db_batch_reset_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(odyssey_P_db_batch_replay_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "O-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on O-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 22 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(odyssey_P_db_put_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_P_db_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(odyssey_P_db_get_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_P_db_get_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(odyssey_P_db_delete_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_P_db_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(odyssey_P_db_has_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_P_db_has_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(odyssey_P_db_compact_size_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_P_db_compact_size_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(odyssey_P_db_batch_put_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_P_db_batch_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(odyssey_P_db_batch_delete_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_P_db_batch_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(odyssey_P_db_batch_reset_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_P_db_batch_reset_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(odyssey_P_db_batch_replay_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_P_db_batch_replay_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "D-Chain Operations per Second",
   "type": "timeseries",
   "description": "Measures how many of each database operation is performed each second across all chains",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ops" } },
   "targets": [
    {
     "expr": "rate(odyssey_C_db_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(odyssey_C_db_get_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(odyssey_C_db_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "rate(odyssey_C_db_has_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "rate(odyssey_C_db_compact_size_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "rate(odyssey_C_db_batch_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "rate(odyssey_C_db_batch_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "rate(odyssey_C_db_batch_reset_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "rate(odyssey_C_db_batch_replay_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  },
  {
   "title": "D-Chain Operations Latency",
   "type": "timeseries",
   "description": "Measures how long each database operation is taking on average on D-Chain",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 29 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(odyssey_C_db_put_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_C_db_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(odyssey_C_db_get_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_C_db_get_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(odyssey_C_db_delete_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_C_db_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(odyssey_C_db_has_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_C_db_has_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(odyssey_C_db_compact_size_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_C_db_compact_size_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(odyssey_C_db_batch_put_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_C_db_batch_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(odyssey_C_db_batch_delete_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_C_db_batch_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(odyssey_C_db_batch_reset_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_C_db_batch_reset_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(odyssey_C_db_batch_replay_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_C_db_batch_replay_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  }
 ]
}