{
 "title": "Odyssey Main Dashboard",
 "description": "Home dashboard with the most important indicators for your node and machine",
 "tags": [ "Odyssey" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "machine", "query": { "query": "label_values(instance)" } },
   { "name": "host", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Uptime average",
   "type": "gauge",
   "description": "Stake weighted average uptime of your node, as reported by network peers. If this falls below 80% node probably won't be rewarded for the current staking period.",
   "gridPos": { "h": 7, "w": 6, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "odyssey_network_node_uptime_weighted_average{instance=~\"$host\", job=~\"odysseygo\"} "
    }
   ]
  },
  {
   "title": "Rewarding stake",
   "type": "gauge",
   "description": "Percentage of the stake that view your node as sufficiently online and correct to vote that node be awarded at the end of the staking period.",
   "gridPos": { "h": 7, "w": 6, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "odyssey_network_node_uptime_rewarding_stake{instance=~\"$host\",job=~\"odysseygo\"}",
     "legendFormat": "Rewarding stake"
    }
   ]
  },
  {
   "title": "A Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the X chain in the last minute",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(odyssey_X_blks_accepted_count{instance=~\"$host\", job=\"odysseygo\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(odyssey_X_blks_rejected_count{instance=~\"$host\", job=\"odysseygo\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Proposed X blocks",
   "type": "stat",
   "description": "Number of A-Chain blocks this node has proposed on the network in the last day. Since block production on O-Chain is usually below the target rate, every node proposes P blocks.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(odyssey_X_blks_built{instance=~\"$host\", job=\"odysseygo\"}[1d]))",
     "legendFormat": "Proposed P blocks"
    }
   ]
  },
  {
   "title": "O Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the P chain in the last minute.",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(odyssey_P_blks_accepted_count{instance=~\"$host\",job=\"odysseygo\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(odyssey_P_blks_rejected_count{instance=~\"$host\",job=\"odysseygo\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Proposed P blocks",
   "type": "stat",
   "description": "Number of O-Chain blocks this node has proposed on the network in the last day. Since block production on O-Chain is usually below the target rate, every node proposes P blocks.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(odyssey_P_blks_built{instance=~\"$host\", job=\"odysseygo\"}[1d]))",
     "legendFormat": "Proposed P blocks"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "gauge",
   "description": "Percentage of CPU used",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(1 - avg(irate(node_cpu_seconds_total{instance=~\"$machine\",job=~\"odysseygo-machine\", mode=~\"idle\"}[1m])) by (instance)) * 100"
    }
   ]
  },
  {
   "title": "Disk Space Used",
   "type": "gauge",
   "description": "Percentage of storage filled",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "max(((node_filesystem_size_bytes{instance=~\"$machine\", job=~\"odysseygo-machine\", fstype=~\"ext4|vfat\"} - node_filesystem_free_bytes{instance=~\"$machine\", job=~\"odysseygo-machine\", fstype=~\"ext4|vfat\"}) / node_filesystem_size_bytes{instance=~\"$machine\", job=~\"odysseygo-machine\", fstype=~\"ext4|vfat\"}) * 100) by (instance)"
    }
   ]
  },
  {
   "title": "Failing health checks",
   "type": "gauge",
   "description": "Number of currently failing internal health checks",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 7 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "odyssey_health_checks_failing{instance=~\"$host\", job=\"odysseygo\",tag=\"all\"}"
    }
   ]
  },
  {
   "title": "Network Latency",
   "type": "stat",
   "description": "Average time to get a response from a peer",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 7 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "odyssey_requests_average_latency{instance=~\"$host\"}"
    }
   ]
  },
  {
   "title": "Total staked",
   "type": "stat",
   "description": "Amount of DIONE currently staked",
   "gridPos": { "h": 5, "w": 3, "x": 0, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "odyssey_P_vm_total_staked{instance=~\"$host\", job=\"odysseygo\"}/1000000000",
     "legendFormat": "DIONE"
    }
   ]
  },
  {
   "title": "Stake connected",
   "type": "stat",
   "description": "Amount of network stake node is currently connected to",
   "gridPos": { "h": 5, "w": 3, "x": 3, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "odyssey_P_percent_connected{instance=~\"$host\", job=\"odysseygo\"}"
    }
   ]
  },
  {
   "title": "Peer count",
   "type": "timeseries",
   "description": "Number of peers node is connected to",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "odyssey_network_peers{instance=~\"$host\", job=\"odysseygo\"}",
     "legendFormat": "Peers"
    }
   ]
  },
  {
   "title": "D Chain Blocks",
   "type": "timeseries",
   "description": "Number of accepted and rejected blocks on the C chain in the last minute.",
   "gridPos": { "h": 6, "w": 9, "x": 12, "y": 12 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(odyssey_C_blks_accepted_count{instance=~\"$host\", job=\"odysseygo\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(odyssey_C_blks_rejected_count{instance=~\"$host\", job=\"odysseygo\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Proposed C blocks",
   "type": "stat",
   "description": "Number of blocks this node has proposed on the D-Chain in the last day. Since D-Chain blocks are produced at a fast rate, block producers are selected by stake weight.",
   "gridPos": { "h": 6, "w": 3, "x": 21, "y": 12 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(odyssey_C_blks_built{instance=~\"$host\", job=\"odysseygo\"}[1d]))",
     "legendFormat": "Built C blocks"
    }
   ]
  },
  {
   "title": "Accepted Blocks",
   "type": "bargauge",
   "description": "Number of blocks accepted in the last minute",
   "gridPos": { "h": 7, "w": 3, "x": 0, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "round(increase(odyssey_X_blks_accepted_count{instance=~\"$host\", job=\"odysseygo\"}[1m]))",
     "legendFormat": "A Chain"
    },
    {
     "expr": "round(increase(odyssey_P_blks_accepted_count{instance=~\"$host\", job=\"odysseygo\"}[1m]))",
     "legendFormat": "O Chain"
    },
    {
     "expr": "round(increase(odyssey_C_blks_accepted_count{instance=~\"$host\", job=\"odysseygo\"}[1m]))",
     "legendFormat": "D Chain"
    }
   ]
  },
  {
   "title": "Blocks processing",
   "type": "bargauge",
   "description": "Number of blocks currently being processed by the node",
   "gridPos": { "h": 7, "w": 3, "x": 3, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "odyssey_X_blks_processing{instance=~\"$host\", job=\"odysseygo\"}",
     "legendFormat": "A Chain"
    },
    {
     "expr": "odyssey_P_blks_processing{instance=~\"$host\", job=\"odysseygo\"}",
     "legendFormat": "O Chain"
    },
    {
     "expr": "odyssey_C_blks_processing{instance=~\"$host\", job=\"odysseygo\"}",
     "legendFormat": "D Chain"
    }
   ]
  },
  {
   "title": "Benched nodes",
   "type": "bargauge",
   "description": "Number of peers currently being benched (ignored) by the node",
   "gridPos": { "h": 7, "w": 3, "x": 6, "y": 17 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "odyssey_X_benchlist_benched_num{instance=~\"$host\", job=\"odysseygo\"}",
     "legendFormat": "A Chain"
    },
    {
     "expr": "odyssey_P_benchlist_benched_num{instance=~\"$host\", job=\"odysseygo\"}",
     "legendFormat": "O Chain"
    },
    {
     "expr": "odyssey_C_benchlist_benched_num{instance=~\"$host\", job=\"odysseygo\"}",
     "legendFormat": "D Chain"
    }
   ]
  },
  {
   "title": "Queries success",
   "type": "bargauge",
   "description": "Percentage of successful queries per chain in the last minute",
   "gridPos": { "h": 7, "w": 3, "x": 9, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "(increase(odyssey_X_handler_chits_count{instance=~\"$host\", job=\"odysseygo\"}[1m]) + 1) / (increase(odyssey_X_handler_chits_count{instance=~\"$host\", job=\"odysseygo\"}[1m]) + increase(odyssey_X_handler_query_failed_count{instance=~\"$host\", job=\"odysseygo\"}[1m]) + 1)",
     "legendFormat": "A Chain"
    },
    {
     "expr": "(increase(odyssey_P_handler_chits_count{instance=~\"$host\", job=\"odysseygo\"}[1m]) + 1) / (increase(odyssey_P_handler_chits_count{instance=~\"$host\", job=\"odysseygo\"}[1m]) + increase(odyssey_P_handler_query_failed_count{instance=~\"$host\", job=\"odysseygo\"}[1m]) + 1)",
     "legendFormat": "O Chain"
    },
    {
     "expr": "(increase(odyssey_C_handler_chits_count{instance=~\"$host\", job=\"odysseygo\"}[1m]) + 1) / (increase(odyssey_C_handler_chits_count{instance=~\"$host\", job=\"odysseygo\"}[1m]) + increase(odyssey_C_handler_query_failed_count{instance=~\"$host\", job=\"odysseygo\"}[1m]) + 1)",
     "legendFormat": "D Chain"
    }
   ]
  },
  {
   "title": "Database Operations Latency",
   "type": "timeseries",
   "description": "How long each database operation is taking on average",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "increase(odyssey_db_put_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "increase(odyssey_db_get_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_get_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "increase(odyssey_db_delete_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "delete"
    },
    {
     "expr": "increase(odyssey_db_has_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_has_count{instance=~\"$host\",job=~\"odysseygo\"}[5m])",
     "legendFormat": "has"
    },
    {
     "expr": "increase(odyssey_db_compact_size_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_compact_size_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "compact"
    },
    {
     "expr": "increase(odyssey_db_batch_put_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_batch_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch put"
    },
    {
     "expr": "increase(odyssey_db_batch_delete_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_batch_delete_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch delete"
    },
    {
     "expr": "increase(odyssey_db_batch_reset_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_batch_reset_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch reset"
    },
    {
     "expr": "increase(odyssey_db_batch_replay_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/increase(odyssey_db_batch_replay_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "batch replay"
    }
   ]
  }
 ]
}