{
 "title": "O-Chain",
 "tags": [ "Odyssey" ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "10s",
 "templating": {
  "list": [
   { "name": "host", "query": { "query": "label_values(instance)" } }
  ]
 },
 "panels": [
  {
   "title": "Accepted Blocks in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(odyssey_P_blks_accepted_count{instance=~\"$host\",job=\"odysseygo\"}[1m]))>0",
     "legendFormat": "Accepted"
    },
    {
     "expr": "round(increase(odyssey_P_blks_acc_count{instance=~\"$host\",job=\"odysseygo\"}[1m]))>0"
    }
   ]
  },
  {
   "title": "Rejected Blocks in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "round(increase(odyssey_P_blks_rejected_count{instance=~\"$host\",job=\"odysseygo\"}[1m]))>0",
     "legendFormat": "Rejected"
    }
   ]
  },
  {
   "title": "Average Block Acceptance Latency",
   "type": "timeseries",
   "description": "The average time between a block's issuance and acceptance by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(odyssey_P_blks_accepted_sum{instance=~\"$host\",job=\"odysseygo\"}[5m]) / rate(odyssey_P_blks_accepted_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "Avg Acceptance Latency"
    }
   ]
  },
  {
   "title": "Average Block Rejection Latency",
   "type": "timeseries",
   "description": "The average time between a block's issuance and rejection by this node over the last 5 minutes.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(odyssey_P_blks_rejected_sum{instance=~\"$host\",job=\"odysseygo\"}[5m]) / rate(odyssey_P_blks_rejected_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "Rejection Latency"
    }
   ]
  },
  {
   "title": "Processing Blocks",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "odyssey_P_blks_processing{instance=~\"$host\",job=\"odysseygo\"}",
     "legendFormat": "Transactions"
    }
   ]
  },
  {
   "title": "Percentage of Successful Queries",
   "type": "timeseries",
   "description": "Percentage of queries for which we receive chits on time.",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "(increase(odyssey_P_handler_chits_count{instance=~\"$host\",job=\"odysseygo\"}[5m]) + 1) / (increase(odyssey_P_handler_chits_count{instance=~\"$host\",job=\"odysseygo\"}[5m]) + increase(odyssey_P_handler_query_failed_count{instance=~\"$host\",job=\"odysseygo\"}[5m]) + 1)",
     "legendFormat": "% Successful"
    }
   ]
  },
  {
   "title": "Message Handling Time (Total)",
   "type": "timeseries",
   "description": "Measures how much of each second is being spent handling different kinds of messages on the O-Chain.\nThe value for chits, for example, is the number of seconds spent handling chits messages per second, over the last 30 seconds.",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(odyssey_P_handler_pull_query_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(odyssey_P_handler_push_query_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(odyssey_P_handler_chits_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(odyssey_P_handler_accepted_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(odyssey_P_handler_get_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(odyssey_P_handler_put_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(odyssey_P_handler_multiput_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(odyssey_P_handler_get_ancestors_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(odyssey_P_handler_get_failed_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(odyssey_P_handler_query_failed_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(odyssey_P_handler_get_accepted_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(odyssey_P_handler_get_ancestors_failed_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(odyssey_P_handler_app_request_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "app request "
    },
    {
     "expr": "rate(odyssey_P_handler_app_request_failed_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "app request failed "
    },
    {
     "expr": "rate(odyssey_P_handler_app_response_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "app response"
    },
    {
     "expr": "rate(odyssey_P_handler_app_gossip_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "app gossip"
    }
   ]
  },
  {
   "title": "Message Handling Time (per Message)",
   "type": "timeseries",
   "description": "Measures how long each kind of request on the O-Chain takes to handle.\nThe value for chits, for example, is how long, in seconds, it takes to handle a chits message.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 24 },
   "fieldConfig": { "defaults": { "unit": "ns" } },
   "targets": [
    {
     "expr": "rate(odyssey_P_handler_pull_query_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_pull_query_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(odyssey_P_handler_push_query_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_push_query_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(odyssey_P_handler_chits_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_chits_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(odyssey_P_handler_accepted_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_accepted_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(odyssey_P_handler_get_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_get_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(odyssey_P_handler_put_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(odyssey_P_handler_multiput_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_multi_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(odyssey_P_handler_get_ancestors_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_get_ancestors_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(odyssey_P_handler_get_failed_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_get_failed_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(odyssey_P_handler_query_failed_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_query_failed_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(odyssey_P_handler_get_accepted_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_get_accepted_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(odyssey_P_handler_get_ancestors_failed_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_get_ancestors_failed_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(odyssey_P_handler_app_request_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_app_request_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(odyssey_P_handler_app_request_failed_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_app_request_failed_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "app request failed"
    },
    {
     "expr": "rate(odyssey_P_handler_app_gossip_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_app_gossip_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "app gossip"
    },
    {
     "expr": "rate(odyssey_P_handler_app_response_sum{instance=~\"$host\",job=\"odysseygo\"}[5m])/rate(odyssey_P_handler_app_response_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "app response"
    }
   ]
  },
  {
   "title": "DIONE Benched",
   "type": "timeseries",
   "description": "The total stake of validators currently \"benched\" due to poor query responsiveness. Queries to these validators will immediately timeout until they are removed from the \"bench.\"",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "avg_over_time(odyssey_P_benchlist_benched_weight{instance=~\"$host\",job=\"odysseygo\"}[15m]) / 10^9",
     "legendFormat": "DIONE Benched"
    }
   ]
  },
  {
   "title": "Messages Received per Second",
   "type": "timeseries",
   "description": "Measures how many of each kind of message are received per second on the O-Chain.",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "rate(odyssey_P_handler_pull_query_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "pull query"
    },
    {
     "expr": "rate(odyssey_P_handler_push_query_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "push query"
    },
    {
     "expr": "rate(odyssey_P_handler_chits_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "chits"
    },
    {
     "expr": "rate(odyssey_P_handler_accepted_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "accepted"
    },
    {
     "expr": "rate(odyssey_P_handler_get_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get"
    },
    {
     "expr": "rate(odyssey_P_handler_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "put"
    },
    {
     "expr": "rate(odyssey_P_handler_multi_put_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "multiput"
    },
    {
     "expr": "rate(odyssey_P_handler_get_ancestors_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get ancestors"
    },
    {
     "expr": "rate(odyssey_P_handler_get_failed_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get failed"
    },
    {
     "expr": "rate(odyssey_P_handler_query_failed_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "query failed"
    },
    {
     "expr": "rate(odyssey_P_handler_get_accepted_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get accepted"
    },
    {
     "expr": "rate(odyssey_P_handler_get_ancestors_failed_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "get ancestors failed"
    },
    {
     "expr": "rate(odyssey_P_handler_app_request_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "app request"
    },
    {
     "expr": "rate(odyssey_P_handler_app_request_failed_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "app request failed"
    },
    {
     "expr": "rate(odyssey_P_handler_app_response_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "app response"
    },
    {
     "expr": "rate(odyssey_P_handler_app_gossip_count{instance=~\"$host\",job=\"odysseygo\"}[5m])",
     "legendFormat": "app gossip"
    }
   ]
  },
  {
   "title": "Block Cache Hit Rate",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 42 },
   "targets": [
    {
     "expr": "increase(odyssey_P_vm_block_cache_hit{instance=~\"$host\"}[5m])/(increase(odyssey_P_vm_block_cache_hit{instance=~\"$host\"}[5m])+increase(odyssey_P_vm_block_cache_miss{instance=~\"$host\"}[5m]))",
     "legendFormat": "Hit Rate"
    }
   ]
  },
  {
   "title": "Unprocessed Incoming Messages",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 0, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "odyssey_P_handler_unprocessed_msgs_len{instance=~\"$host\"}",
     "legendFormat": "Pending Messages"
    }
   ]
  },
  {
   "title": "Incoming Messages Expired in Last Minute",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 8, "x": 8, "y": 50 },
   "fieldConfig": { "defaults": { "unit": "short" } },
   "targets": [
    {
     "expr": "increase(odyssey_P_handler_expired{instance=~\"$host\"}[1m])",
     "legendFormat": "Expired"
    }
   ]
  }
 ]
}